"""create users and measurements

Revision ID: c94b75d53c19
Revises: 
Create Date: 2026-10-08 18:12:36.101928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94b75d53c19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('height', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.CheckConstraint('height >= 130 AND height <= 230', name='check_height_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('muscles', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('bones', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('water', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.CheckConstraint('bones >= 0.5 AND bones <= 7', name='check_bones_range'),
    sa.CheckConstraint('fat >= 2 AND fat <= 60', name='check_fat_range'),
    sa.CheckConstraint('muscles >= 15 AND muscles <= 55', name='check_muscles_range'),
    sa.CheckConstraint('water >= 35 AND water <= 75', name='check_water_range'),
    sa.CheckConstraint('weight >= 30 AND weight <= 400', name='check_weight_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    op.drop_table('users')
    # ### end Alembic commands ###
